print('hello world!')
print('開業しない',end=' ')
print('うんこ')
#print('omae namae \n>',end=' ')
#name = input()
#print('名前は',name,'だ')
a = int(input('a = '))
f = float(input('f = '))
print('a + f ={}です'.format(a + f))
print('a * f = ',a*f,'desu',sep = '')
